name: Minimal Android CI Workflow

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-apk:
    name: Generate APK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Client/CampusLink
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build gradle project
        run: ./gradlew build
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace  
      - name: Find APK
        run: cd build | ls 
  upload-apk:
    name: Upload APK
    needs: build-apk
    runs-on: ubuntu-latest
    steps:
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: Client/CampusLink
          
#   release:
#     name: Release APK
#     needs: upload-apk
#     if: startsWith(github.ref, 'refs/tags/v')
#     runs-on: ubuntu-latest
#     steps:
#       - name: Download APK from build
#         uses: actions/download-artifact@v1
#         with:
#           name: apk  
#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
#         with:
#           tag_name: ${{ github.ref }}
#           release_name: Release ${{ github.ref }} 
#       - name: Upload Release APK
#         id: upload_release_asset
#         uses: actions/upload-release-asset@v1.0.1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           upload_url: ${{ steps.create_release.outputs.upload_url }}
#           asset_path: apk/app-debug.apk
#           asset_name: MensaApp.apk
#           asset_content_type: application/zip
