name: Minimal Android CI Workflow

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  open-dir:
    name: Open App Directory
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Client/CampusLink
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: List files
        run: ls
  build-apk:
    name: Generate APK
    needs: open-dir
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Client/CampusLink
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace

